### ISSUE TITLE
MAX command 

### ISSUE THREAD

**Issue by smartclash** [BerkanYildiz/UCS#1]
As per my knowledge, there was a max command at ucs 0.6.3.1. And i would like that same command to be implemented at 0.6.5.0

You team have done an amazing thing and I am so happy at your progress.

**Comment by aididhaiqal** [comment]
For now,We will focus on main arch until we finish clan and fix building issue.After that we will start implementing useful thing

**Comment by BerkanYildiz** [comment]
The command has been added.

**Comment by smartclash** [comment]
@BerkanYildiz Thanks for adding it. You may now close this issue

**Comment by smartclash** [comment]
@BerkanYildiz Oops, didn't notice you've closed it!
