### ISSUE TITLE
For PVP we should Remove sheild! so users cant Attack to other players! becuase Sheild Time manager not work probably!! 

### ISSUE THREAD

**Issue by DaividSmith** [BerkanYildiz/UCS#13]
For PVP we should Remove sheild for every time play game! so users cant Attack to other players! becuase Sheild Time manager not work probably!! and always all player have sheild!!
so i think sheild should disable temporary till players can attack to each others

**Comment by aididhaiqal** [comment]
player can attack each other even there is a shield because pvp core is not fully implemened

**Comment by DaividSmith** [comment]
so for now its OK? i cant attack to my acount when my sheild is Active...
