### ISSUE TITLE
Clear Obstacles

### ISSUE THREAD

**Issue by fhxserver** [BerkanYildiz/UCS#25]
Can not eliminate Obstacles. Trees, rocks, etc. are cleaned, always turning as before.

**Comment by smartclash** [comment]
@fhxserver as said,  it is alpha.  Please wait till it gets fully implemented. Thanks for pointing out this issue

**Comment by aididhaiqal** [comment]
I think its solved,Please check it and comment.If work i will close this issue

**Comment by fhxserver** [comment]
Yep, now it is working fine, but the bugs here, so can not login. See : http://image.prntscr.com/image/73f3442c6c7e434cb653d59b36fe6414.jpg

**Comment by aididhaiqal** [comment]
You may try this new commit that fix avatar stream message being sended even clan is not available https://github.com/BerkanYildiz/UCS/commit/7b124400586074e30f608c4ed7d793d30ce03cef
