### ISSUE TITLE
Error with mysql

### ISSUE THREAD

**Issue by Abrek** [BerkanYildiz/UCS#31]
ult rev for this moment

> System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
    System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
    System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
    System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
    System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
    System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
    System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
    System.Data.Entity.Internal.Linq.InternalSet`1.FindInStore(WrappedEntityKey key, String keyValuesParamName)
    System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
    UCS.Core.DatabaseManager.Save(List`1 avatars) в E:\server\UcServer\soft\compile\Ultrapowa Clash Server\Core\DatabaseManager.cs:line 284
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'Extent1.IPAddress' in 'field list'
    MySql.Data.MySqlClient.MySqlStream.ReadPacket()
    MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
    MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
    MySql.Data.MySqlClient.MySqlDataReader.NextResult()
    MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
    MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
    System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
    System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
 System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

**Comment by smartclash** [comment]
@Abrek can you please further explain the steps done by you. Can I get a copy of ucs.exe and ucsconf.config file? Please explain us what you did before getting this error.

**Comment by Abrek** [comment]
No did nothing. just start the server
https://uploadify.net/c50a181f247920df/ucse.rar

**Comment by aididhaiqal** [comment]
Hello,I think you use latest ucs without cleaning database 

> Unknown column 'Extent1.IPAddress' in 'field list' MySql.Data.MySqlClient.MySqlStream.ReadPacket()

**Comment by Abrek** [comment]
DB is clean, i reinstalled DB

**Comment by aididhaiqal** [comment]
Did you import latest ucsdb.sql file?

**Comment by Abrek** [comment]
yes, last

**Comment by smartclash** [comment]
Every thing works good to us. I think it is a problem with your software. Issue closed!!

**Comment by Abrek** [comment]
This error when use mysql with password, without pass work fine ))
But mysql without password no good for security.
