### ISSUE TITLE
GUI NOT RESPONDING

### ISSUE THREAD

**Issue by fhxserver** [BerkanYildiz/UCS#36]
Hello , Gui Error after 500 login. Check the image below :
http://image.prntscr.com/image/19872a51519c478c900ffc1d8cb1b63b.jpg

**Comment by BerkanYildiz** [comment]
I don't see any problem on the image.

**Comment by fhxserver** [comment]
Okay , that's actually not responding . diserver try and clay shard what happened .

**Comment by ADeltaX** [comment]
Try disabling Debug Mode.

**Comment by ADeltaX** [comment]
If not, switch to console mode.

**Comment by iSwuerfel** [comment]
You have to disable the debug Mode till a fix will arrive today.
#Closed
