### ISSUE TITLE
Warning not fixed !!!

### ISSUE THREAD

**Issue by TokyoSU** [BerkanYildiz/UCS#39]
Please look this image:

http://img15.hostingpics.net/pics/874896Error.png

**Comment by aididhaiqal** [comment]
try reclone and you should get no error at all (Maybe only one because app.manifest which you can delete)

**Comment by aididhaiqal** [comment]
Btw,I think warning is safe to ignore until gui department finish it

**Comment by aididhaiqal** [comment]
Fixed https://github.com/BerkanYildiz/UCS/commit/73c81201c66a5c611ddc1520539f6321d584f632
