### ISSUE TITLE
Crash after much player

### ISSUE THREAD

**Issue by fhxserver** [BerkanYildiz/UCS#5]
Hello As the title suggests, I have tried to use this emulator to run my server, when approximately 100 login, this emulator directly not responding. Crash after this commit https://github.com/BerkanYildiz/UCS/commit/7206daf3221f1763731c103d4bd170ea8a4ef914. Before you commit it, the emulator runs smoothly.

**Comment by BerkanYildiz** [comment]
I will test it on shard and see what throw this error.
Thanks for the report.

**Comment by iSwuerfel** [comment]
How you will test it at Shard?

**Comment by BerkanYildiz** [comment]
by killing you

**Comment by iSwuerfel** [comment]
Mhm no, you won't kill me. ^^

**Comment by iSwuerfel** [comment]
Just relax, Berkan, relaaaaaaaaaaaaax.

**Comment by aididhaiqal** [comment]
I know this problem,Its because  new pvp searching system,I will disable it for a while

**Comment by aididhaiqal** [comment]
If crash still exist,Please reopen the thread

**Comment by iSwuerfel** [comment]
The crash is not because of the PvP System (proofed with Shard)

**Comment by iSwuerfel** [comment]
Handled with: https://github.com/BerkanYildiz/UCS/commit/7cd50f39999ba1e22b78d7cb92b07e3be78404ae

Closed
