### ISSUE TITLE
Cannot show debug

### ISSUE THREAD

**Issue by fhxserver** [BerkanYildiz/UCS#8]
Can not see the debug mode as incoming connections, online players, etc. ex : localhost:1172/debug.

**Comment by iSwuerfel** [comment]
Thanks for the report! We will take care of it.

**Comment by aididhaiqal** [comment]
Localhost:1172/debug is not implemented yet in 0.6.5.0 Version. FYI,You can use /status in ucs console ATM

**Comment by fhxserver** [comment]
Enable gui ?

**Comment by aididhaiqal** [comment]
Gui also disabled for the moment

**Comment by fhxserver** [comment]
How to use /status ?
