### ISSUE TITLE
[UCS] UCS.Core.Debugger problem

### ISSUE THREAD

**Issue by smartclash** [BerkanYildiz/UCS#9]
As per the `master` branch, not the release section i think there is an issue with the code. I downloaded the code, tried to compile it and it threw an exception `System.TypeInitializationException` occurred in Ultrapowa Clash Server.exe 

Please review the code. If it's my problem, i am really sorry for it but i think it's a problem of code.

Regards,
Karan sanjeev

**Comment by iSwuerfel** [comment]
The master branch is not supported as it is an extremely old version.
